global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
      - region: us-east-1
        #role_arn: arn:aws:iam::980136594430:role/Ec2-Instance-Role
        filters:
        - name: tag:aws:cloudformation:logical-id
          values:
          - EcsInstanceAsg
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
      - region: us-east-1
        #role_arn: arn:aws:iam::980136594430:role/Ec2-Instance-Role
        filters:
        - name: tag:aws:cloudformation:logical-id
          values:
          - EcsInstanceAsg
